name: Run Postman Tests with Newman

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm install
          npm install -g newman # Install Newman globally

      # Step 4: Run the Postman collection
      - name: Run Postman tests
        run: |
          newman run shop_items.postman_collection.json
